//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotelyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEnroll
    {
        public int UserEnrollID { get; set; }
        public int ActivityID { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> UserEnrollStart { get; set; }
        public System.DateTime UserEnrollActivityStart { get; set; }
        public System.DateTime UserEnrollActivityEnd { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public string Remark { get; set; }
        public short Status { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
