//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    
        public Activity()
        {
            this.ActivityDetail = new HashSet<ActivityDetail>();
            this.UserEnroll = new HashSet<UserEnroll>();
        }
    
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
        public string ActivityIcon { get; set; }
        public int ActivityTypeID { get; set; }
        public string ActivityAddress { get; set; }
        public Nullable<decimal> ActivityAddressX { get; set; }
        public Nullable<decimal> ActivityAddressY { get; set; }
        public string ActivityContent { get; set; }
        public int ActivityPrediNum { get; set; }
        public int ActivityManagerID { get; set; }
        public Nullable<int> ActivityApplyUserInfoID { get; set; }
        public Nullable<int> ActivityApplyOrganizeID { get; set; }
        public int ActivityClicks { get; set; }
        public System.DateTime ActivityEnrollEnd { get; set; }
        public System.DateTime ActivityEnrollStart { get; set; }
        public Nullable<System.DateTime> ActivityStart { get; set; }
        public Nullable<System.DateTime> ActivityEnd { get; set; }
        public string ActivityPolitical { get; set; }
        public string ActivityMajor { get; set; }
        public string ActivityDepartment { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public string Remark { get; set; }
        public short Status { get; set; }
        public string ActivityAddressDetail { get; set; }
    
        public virtual OrganizeInfo ApplyOrganizeInfo { get; set; }
        public virtual UserInfo ApplyUserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityDetail> ActivityDetail { get; set; }
        public virtual UserInfo ManagerUserInfo { get; set; }
        public virtual ActivityType ActivityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEnroll> UserEnroll { get; set; }
    }
}
